# application.yml
--- 
spring: 
  application: 
    name: test
server: 
  port: ${PORT:${SERVER_PORT:0}}
words: to,pass,the,test

--- 
spring: 
  profiles: vendite
  application: 
    name: vendite
sales: 18000,16000,21000,30000,37000,150000,26000,1800000,96000
server: 
  port: 8082
  


